#!/bin/sh

# Use Xresources
xrdb -merge $XDG_CONFIG_HOME/Xresources &

#Autostart 
remap &
#setbg &
#displayselect &
dunst &
#xcompmgr &		# xcompmgr for transparency
#xset r rate 300 50 &	# Speed xrate up

exec i3
