#!/bin/sh

xrdb -merge $XDG_CONFIG_HOME/Xresources &

#Autostart 
remap &
dunst &
xcompmgr &
autorandr --change &
firefox &
blueman-applet &
crond -f "$XDG_CONFIG_HOME/crontab" &
mpd &
displayselect &
redshift -P -O 2700 &

exec i3
