#!/bin/sh

[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
    1)  ;; # left click, 
    4)  ;; # scroll up, 
    5)  ;; # scroll down, 
    *)  ;;
esac

status=$(acpi)

true && echo "${status}" || echo "MUTE"
