#!/bin/sh

state=$(acpi -b | sed 1q | cut -d" " -f3 | tr -d ',')
status=$(acpi -b | sed 1q | cut -d" " -f4 | tr -d ',')
time=$(acpi -b | sed 1q | cut -d" " -f5 | tr -d '\n')
[ -n "${time}" ] && status="${status} (${time})"

if [ "${state}" = "Discharging" ]; then prefix="-"
elif [ "${state}" = "Charging" ]; then prefix="+"
else prefix=""; fi

echo "${prefix}${status}"
