#!/bin/sh

case "${BLOCK_BUTTON}" in
    1) redshift -O 2500 > /dev/null 2>&1 ;; # left click, enable redshift
    2) xbacklight 0 ;; # middle click, set 0
    3) xbacklight 100 && redshift -P -O 5500 > /dev/null 2>&1 ;; # right click, reset
    4) xbacklight +5 ;; # scroll up, increase
    5) [ $(xbacklight -get) -lt 6 ] && xbacklight 1 || xbacklight -5 ;; # scroll down, decrease
esac

echo $(xbacklight -get)
