#!/usr/bin/env perl
use Time::HiRes qw(usleep);
use Env qw(BLOCK_INSTANCE);

use constant DELAY => 50;
use constant SPOTIFY_STR => 'spotify';

my @metadata = ();
my $player_arg = "";

if ($BLOCK_INSTANCE) {
    $player_arg = "--player='$BLOCK_INSTANCE'";
}

sub buttons {
    my $method = shift;
    if ($ENV{'BLOCK_BUTTON'} == 5) {
        system("mpc prev");
    } elsif ($ENV{'BLOCK_BUTTON'} == 1) {
        system("mpc toggle");
    } elsif ($ENV{'BLOCK_BUTTON'} == 4) {
        system("mpc next");
    }
}

sub mpd {
    my $data = qx(mpc current);
    if (not $data eq '') {
        buttons("mpd");
        print("🎵 ");
        print($data);
        exit 0;
    }
}

mpd;
print("\n");
