#!/bin/sh

case "${BLOCK_BUTTON}" in
    1) mpc toggle > /dev/null 2>&1 ;; # left click, pause
    2) mpc random > /dev/null 2>&1 ;; # middle click, randomize playlist
    3) mpc repeat > /dev/null 2>&1 ;; # right click, repeat current song
    4) mpc prev > /dev/null 2>&1 ;; # scroll up, next song
    5) mpc next > /dev/null 2>&1 ;; # scroll down, previous song
esac

[ -n "$(mpc status | grep paused)" ] && paused="P"
[ "$(mpc status | tail -n 1 | awk '{print $6}')" = "on" ] && random="S"
[ "$(mpc status | tail -n 1 | awk '{print $4}')" = "on" ] && repeat="R"

current=$(mpc current)
[ -n "${current}" ] && echo "$paused$random$repeat | $current"
