#!/bin/sh

#todo add possibility to change location and switch formats with clicks
#[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
#    1)  ;; # left click, 
#    4)  ;; # scroll up, 
#    5)  ;; # scroll down, 
#    *)  ;;
#esac

    if [ "$(checkupdates | wc -l)" -le 0 ]; then
        upd=""
    else
        upd="${red} ${normal}${upd} "
    fi
