#!/bin/sh

[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
    1) [ "$(checkupdates | wc -l)" -gt 0 ] && notify-send "Installing updates..." && pikaur -Syu --noconfirm > /dev/null 2>&1 && notify-send "Updates installed" ;; # left click, 
    *)  ;;
esac

status=$(checkupdates | wc -l)
[ "${status}" != 0 ] && echo "${status}"
