#!/bin/sh

[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
    1) # left click, show ip address
       ip=$(ip addr | grep 'UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/') && notify-send "${ip}" ;;
    *) ;;
esac

[ ! -d /sys/class/net/wlan0/wireless ] || [ "$(cat /sys/class/net/wlan0/operstate)" = 'down' ] && exit

ESSID=$(wpa_cli -i wlan0 list_network | grep CURRENT | cut -f 2)
QUALITY=$(grep wlan0 /proc/net/wireless | awk '{ print int($3) }')

echo "${ESSID} (${QUALITY}%)"
