#!/bin/sh

# System maintenance
alias kop='sudo $(history -p !!)'
alias mdot='git --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME'
alias off='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias ssys='sudo systemctl'
alias paux='ps -aux | grep'
alias p='ping 8.8.8.8'
alias ...='cd ../..'
alias ....='cd ../../../'

#Package maintenance
alias aur='pikaur'
alias syu='pikaur -Syyuu'
alias sp='sudo pacman'
alias S='sudo pacman -S'
alias Rns='sudo pacman -Rns'
alias Qs='sudo pacman -Qs'
alias Ss='sudo pacman -Ss'

# Default parameters 
alias c='clear'
alias l='ls -hNF' 
alias la='ls -ANF'
alias ll='ls -AlF'
alias cd..='cd ..'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -v'
alias mkdir='mkdir -pv'

# XDG_CONFIG workarounds
alias wget='sudo wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias gpg2='gpg2 --homedir "$XDG_DATA_HOME/gnupg"'
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc"'
alias weechat='weechat -d "$XDG_CONFIG_HOME/weechat"'

# Program shortcuts
alias a='alsamixer'
alias gadd='git add .'
alias gstat='git status'
alias gcom='git commit -m'
alias gpush='git push'
alias m='neomutt'
alias n='ncmpcpp 2>/dev/null'
alias nw='newsboat -q'
alias o='xdg-open $@ 2>/dev/null'
#function o(){ xdg-open $@ 2> /dev/null & }
alias r='ranger'
alias v='$EDITOR'
alias sv='sudo $EDITOR'
alias z='tabbed -c zathura -e'
alias wifi='sudo wifi-menu'
alias docked='autorandr docked'
alias mobile='autorandr mobile'

# Colors
alias ls='ls --color=auto --group-directories-first'
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ip='ip -c'
alias diff='diff --color'

cdls () { builtin cd "$@" && ls; }
alias cd='cdls'
alias ..='cd ..'

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Youtube
alias yt='youtube-dl -o "~/Video/%(title)s.%(ext)s" --restrict-filenames -ic --hls-prefer-ffmpeg --add-metadata'
alias yta='youtube-dl -o "~/Music/%(artist)s -%(album)s - %(title)s.%(ext)s" --restrict-filenames -xic --audio-format "mp3" --hls-prefer-ffmpeg --add-metadata'

function ytb() {
    (mpv --ytdl-format="bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best" ytdl://ytsearch:"$*" < /dev/null &>/dev/null &);
}

# Printer
cupsadm() { /bin/firefox "http://localhost:631"; }
