#!/bin/sh

# System maintenance
alias kop='sudo $(history -p !!)'
alias mdot='git --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME'
alias off='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias ssys='sudo systemctl'
alias paux='ps -auxwf | grep'
alias p='ping 1.1.1.1'
alias ...='cd ../..'
alias ....='cd ../../../'
alias rmf='rm -rf'
#alias docked='autorandr docked'
#alias mobile='autorandr mobile'
alias emu='autorandr emu'

#Package maintenance
alias aur='pikaur'
alias syu='pikaur -Syyuu'
alias sp='sudo pacman'
alias S='sudo pacman -S'
alias Rns='sudo pacman -Rns'
alias Qs='sudo pacman -Qs'
alias Ss='sudo pacman -Ss'

# Default parameters 
alias c='clear'
alias l='ls -lhNF' 
alias la='ls -ANF'
alias ls='ls -hNF'
alias ll='ls -AlhF'
alias cd..='cd ..'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -v'
alias mkdir='mkdir -pv'
alias urlscan='urlscan -csH'

# XDG_CONFIG workarounds
alias abook='abook --config "$XDG_CONFIG_HOME/abook/abookrc" --datafile "$XDG_DATA_HOME/abook/addressbook"'
alias wget='sudo wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias gpg2='gpg2 --homedir "$XDG_DATA_HOME/gnupg"'
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc"'
alias tor-browser='setsid nohup tor-browser-en --dir=$XDG_CONFIG_HOME/tor > /tmp/tor-browsernohup.out 2>&1'
alias weechat='weechat -d "$XDG_CONFIG_HOME/weechat"'

# Program shortcuts
alias a='alsamixer'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gs='git status'
alias m='neomutt'
alias n='ncmpcpp 2>/dev/null'
alias news='newsboat -q'
alias o='rifle'
alias r='ranger'
alias v='$EDITOR'
alias vp='$EDITOR $_'
alias pwgen='pass generate --clip'
alias stream='ffmpeg -f x11grab -video_size 1920x1080 -framerate 25 -i $DISPLAY -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac screen.mp4'
alias sv='sudo $EDITOR'
alias z='setsid nohup zathura > /tmp/zathuranohup.out 2>&1'
alias fetch='neofetch'
alias wifi='sudo wifi-menu'

# Colors
alias ls='ls --color=auto --group-directories-first'
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ip='ip -c'
alias diff='diff --color'

cdls () { builtin cd "$@" && l; }
alias cd='cdls'
alias ..='cd ..'

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Youtube
alias ytv='youtube-dl -o "~/video/%(title)s.%(ext)s" --restrict-filenames -ic -f best --hls-prefer-ffmpeg --add-metadata'
alias yta='youtube-dl -o "~/music/%(artist)s-%(title)s.%(ext)s" --restrict-filenames -xic -f bestaudio/best --hls-prefer-ffmpeg --add-metadata'

# Printer
cupsadm() { /bin/firefox "http://localhost:631"; }
