#!/bin/sh

# Source Xresources
xrdb -merge $XDG_CONFIG_HOME/xorg/Xresources &

#Autostart 
remap &
dunst &
xcompmgr &
autorandr --change &
firefox &
blueman-applet &
ssh proxy -N &
signal-desktop --start-in-tray &
caprine &
spotify-tray --minimized &
discord --start-minimized &
crond -f "$XDG_CONFIG_HOME/crontab" &
mpd &
redshift -P -O 2700 &

exec i3 
