#!/bin/sh

# Source Xresources
xrdb -merge $XDG_CONFIG_HOME/xorg/Xresources &

#Autostart 
remap &
dunst &
xcompmgr &
autorandr --change &
firefox &
blueman-applet &
crond -f "$XDG_CONFIG_HOME/crontab" &
mpd &
redshift -P -O 2700 &

exec i3 
